[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "deepgram-sdk>=4.8.0",
    "livekit-agents>=1.2.2",
    "openai>=1.98.0",
    "python-dotenv>=1.1.1",
]
